### PR TITLE
Extra docs

### PR DESCRIPTION
**Pull request by rreusser**
See: #1. I think this covers most of the basics so that some browsing npmjs.com can judge effectively. Let me know if changes desired. Otherwise a version bump, a publish, and should be good to go. Thanks!

### CODE REVIEW

**Comment by rreusser** [comment]
Oops. Just a second. Adding a quick reference to `loose-interleave`.

**Comment by rreusser** [comment]
Okay, all good on my end. :+1:

**Comment by jarofghosts** [comment]
Thanks for this!

**Comment by rreusser** [comment]
Np. Thank you!

**Pull request merged**
